<div class="sidebar" id="sidebar">
    <!-- Logo -->
        <div class="sidebar-logo">
                <a href="{{ route('home') }}" class="logo logo-normal">
                            <img src="{{ asset('assets/img/logo.svg') }}" alt="Orange Mali RH">
                                    </a>
                                            <a href="{{ route('home') }}" class="logo-small">
                                                        <img src="{{ asset('assets/img/logo-small.svg') }}" alt="Orange Mali RH">
                                                                </a>
                                                                        <a href="{{ route('home') }}" class="dark-logo">
                                                                                    <img src="{{ asset('assets/img/logo-white.svg') }}" alt="Orange Mali RH">
                                                                                            </a>
                                                                                                </div>
                                                                                                    <!-- /Logo -->
                                                                                                        <div class="modern-profile p-3 pb-0">
                                                                                                                <div class="text-center rounded bg-light p-3 mb-4 user-profile">
                                                                                                                            <div class="avatar avatar-lg online mb-3">
                                                                                                                                            <img src="{{ asset('assets/img/profiles/avatar-02.jpg') }}" alt="Img"
                                                                                                                                                                class="img-fluid rounded-circle">
                                                                                                                                                                            </div>
                                                                                                                                                                                        <h6 class="fs-12 fw-normal mb-1">{{ Auth::user()->name }}</h6>
                                                                                                                                                                                                    <p class="fs-10">RH - Gestion des employés et congés</p>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                    <div class="sidebar-inner slimscroll">
                                                                                                                                                                                                                            <div id="sidebar-menu" class="sidebar-menu">
                                                                                                                                                                                                                                        <ul>
                                                                                                                                                                                                                                                        <li class="menu-title"><span>MENU RH</span></li>
                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                            <a href="{{ route('home') }}">
                                                                                                                                                                                                                                                                                                                    <i class="ti ti-smart-home"></i><span>Tableau de bord</span>
                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                            <a href="{{ route('employees.index') }}">
                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="ti ti-users"></i><span>Employés</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="{{ route('leaves.index') }}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="ti ti-calendar-event"></i><span>Congés</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="{{ route('attendances.index') }}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="ti ti-clock"></i><span>Pointage</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="{{ route('employees.index') }}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="ti ti-briefcase"></i><span>Postes</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="{{ route('contracts.index') }}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="ti ti-file-text"></i><span>Contrats</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li class="submenu">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="javascript:void(0);"><i class="ti ti-building"></i><span>Départements</span> <span class="menu-arrow"></span></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ul style="display: none;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Direction générale</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Ressources humaines</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Finance</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Commercial</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Marketing</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Digital</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">IT / Systèmes</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Juridique</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Qualité</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Logistique</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Service client</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Approvisionnement</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li><a href="#">Sécurité</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="{{ route('users.index') }}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <i class="ti ti-user"></i><span>Utilisateurs</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="{{ route('logout') }}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onclick="event.preventDefault(); document.getElementById('logout-form-sidebar').submit();">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <i class="ti ti-logout"></i><span>Déconnexion</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <form id="logout-form-sidebar" action="{{ route('logout') }}" method="POST" class="d-none">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @csrf
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        